### ISSUE TITLE
 the dates don’t generate properly 

### ISSUE THREAD

**Issue by cnio** [LouisBarranqueiro/hexo-theme-tranquilpeak#253]
Hello! Thanks for the great theme.

Here is some wrong when generate the date, and this is my date displaying:
```
4amt4_for0amt post.categorized_in Javascript
```
what am i miss sth configuration?
also my site is https://wem.me

thanks a lot in advance!!

**Comment by LouisBarranqueiro** [comment]
Hey man, oh yeah, It seems that the problem come from languages files. What is your main language? Could you add your main `_config.yml` file, please?

**Comment by cnio** [comment]
yeah, my file as follows:
```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Web Experience Master 
subtitle: 
description:
author: CNIO
language: en
timezone: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://wem.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: peak
feed:
    type: atom
    path: atom.xml
    limit: 20

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy: 
  type: git
  repository: git@github.com:cnio/b.git
```
