### ISSUE TITLE
The Button which control sidebar open and close cannot work

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [LouisBarranqueiro/hexo-theme-tranquilpeak#296]
### Configuration

 - **Operating system with version** : 
 - **Node version 5.6.0 : 
 - **Hexo version 3.2.2 : 
 - **Hexo-cli version 1.0.2 : 
 - **Tranquilpeak version 1.9.0 : 
 

### Actual behavior
After I install the Hexo by the official document, I choose this theme. And I configuration the config.yml according to the user document. But there is a problem!
The Button which control sidebar open and close cannot work.There this no response when I tab or click it.
Can you give me some help? Thanks!

**Comment by LouisBarranqueiro** [comment]
Hey @ZhiXingHeYiApple, 
Which browser do you use?
Is there any errors in the console of the browser when you click on the button?

**Comment by jamespedwards42** [comment]
I have this same issue after moving from 1.8.1 to 1.9.  Confirmed with both Chrome 52.0.2743.60 beta (64-bit) and Safari 9.1.1.  Moved back to 1.8.1 and no issues.

**Comment by LouisBarranqueiro** [comment]
Is there any error messages in the console?

**Comment by jamespedwards42** [comment]
I will sit down tonight and move back to 1.9 to see if there are any errors.

```yaml
sidebar:
    menu:
        home:
            title: global.home
            url: /
            icon: home
        categories:
            title: global.categories
            url: /all-categories
            icon: bookmark
        tags:
            title: global.tags
            url: /all-tags
            icon: tags
        archives:
            title: global.archives
            url: /all-archives
            icon: archive
    author_links:
        github:
            title: global.github
            url: https://github.com/jamespedwards42
            icon: github
        twitter:
            title: global.twitter
            url: https://twitter.com/jamespedwards
            icon: twitter
        keybase:
            title: Keybase
            url: https://keybase.io/jamespedwards42
            icon: key
        mail:
            title: global.mail
            url: mailto:james.p.edwards42@gmail.com
            icon: envelope-o
```
