### ISSUE TITLE
Archive for month is does't work, how can I fixes it?

### ISSUE THREAD

**Issue by zssr** [LouisBarranqueiro/hexo-theme-tranquilpeak#342]
### Configuration

 - **Operating system with version** : OS X El Capitan
 - **Node version** : 6.2.1
 - **Hexo version** : 
 - **Hexo-cli version** : 1.0.1
 - **Tranquilpeak version** :  1.8 original except deleting catogories 
 

### Actual behavior
I clicked Archives -> September -> oops: 404 (http://zssr.github.io/archives/2016/09)

**Comment by LouisBarranqueiro** [comment]
Hey @zssr,

Since it's working on demo site, maybe you have ghost archives. Try to run `hexo clean` to remove them. and try again.

**Comment by zssr** [comment]
It is deployed from a newly generated hexo directory. (`hexo init`).  

I runned `hexo clean` but it still won't work. (`archieves/2016` and `archieves/2016/09`  directory`*Page Not Found*`).

**Comment by zssr** [comment]
It is deployed from a newly generated hexo directory. (`hexo init`).  

I runned `hexo clean` but it still won't work. (`archieves/2016` and `archieves/2016/09`  directory`*Page Not Found*`).

**Comment by LouisBarranqueiro** [comment]
As you can see archives are at the blog root and  not in the archives folder that's why there is a 404 error. Could you add your main config.yml please?
![capture d ecran 2016-09-19 a 17 29 28](https://cloud.githubusercontent.com/assets/4705626/18638010/bc4feb68-7e8e-11e6-82eb-c4e38e96a3ad.png)

**Comment by zssr** [comment]
Here it is. (Since GitHub doesn't support .yml file type, I pasted the content below.)

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 煮石散人
subtitle:
description:
author: zssr
language: en
timezone:
since: 2015

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zssr.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Feed
feed:
    type: atom
    path: atom.xml
    limit: 20

# Global keywords for search engines
keywords:
# - hexo
# - javascript

# Generator-archive
archive_generator:
  per_page: 20
  yearly: false
  monthly: false
  daily: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: tranquilpeak

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/zssr/zssr.github.io
```
