### ISSUE TITLE
How do I add a new font-awesome icon in side bar ?

### ISSUE THREAD

**Issue by anurag-jain** [LouisBarranqueiro/hexo-theme-tranquilpeak#377]
I'm unable to add a new social icon getting displayed in the sidebar. I tried to edit the _config.yml file in theme and added the following under author_links.
```
 500px:
            title: global.500px
            url: https://500px.com/a4anurag
            icon: 500px
```
Also theme was containing old version of font awesome and thus I replaced the filed under source\assets\fonts and source\assets\css with the ones from new version of font-awesome in addition to the variable name in en.yml.
I see the text 500px but the icon doesn't appear. What am I missing here ?
