### ISSUE TITLE
.gitignore error

### ISSUE THREAD

**Issue by ccapasso01** [LouisBarranqueiro/hexo-theme-tranquilpeak#523]
### Configuration

 - **Operating system with version** :  macOS Mojave
hexo-cli: 1.1.0
os: Darwin 18.0.0 darwin x64
http_parser: 2.8.0
node: 8.11.3
v8: 6.2.414.54
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2o
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
 - **Tranquilpeak version**: Original
 - **Site configuration file** (Optional):
 - **Theme configuration file** (Optional):
 - **Hexo plugin** (Optional): 
 
### Actual behavior
Theme does not render properly when published to gitlab.  This is because .gitignore has assets in it.  As such, the asset are not loading.

### Expected behavior
Expect page to load with all assets

### Steps to reproduce the behavior
get fresh copy of template and push to gitlab. 
after removing assets from .gitignore and pushing, the site rendered properly.  I checked the source and .gitignore shows assets in it.

**Comment by ccapasso01** [comment]
@LouisBarranqueiro  - Thanks for that.  Maybe I am doing something incorrect.  Here is what I have been doing:

1. My repo is cloned to my computer and opened in VSCode.
2. I installed your theme and modified as necessary.
3. I then push my cloned repo back to my master branch on gitlab (using that instead of github).
4. This triggers a pipeline to run automatically using the following:

```
image: node:8.11.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install
  - hexo generate
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
```

5. Once that is done, my page is accessible on gitlab pages.
