### ISSUE TITLE
click "Home" on sidebar, url turn to be "http://localhost:4000/%20/"

### ISSUE THREAD

**Issue by wangyangang** [LouisBarranqueiro/hexo-theme-tranquilpeak#589]
### Description
when i click the home button on sidebar, web browser go to "http://localhost:4000/%20/",
other button on sidebar work fine but home button.

### Expected behavior
web browser go to "http://localhost:4000/" or "http://localhost:4000"

### Steps to reproduce the bug
 I follow your documentation to config this theme on my website,
it occur.

### Environment
 - **Operating system with version** : Macos catalina 10.15.1
 - **Node version**: v10.16.0
 - **Hexo version**: 4.0.0
 - **Hexo-cli version**: 2.0.0

### Additional information
- [* ] I can fix this bug 
by edit _config.yml file:
```
sidebar:
    menu:
        home:
            title: global.home
            # url: /            # change this line with next line.
            url: ""
```
