### ISSUE TITLE
Modify inline code color in `_base.scss` not working

### ISSUE THREAD

**Issue by secsilm** [LouisBarranqueiro/hexo-theme-tranquilpeak#698]
First of all, Thanks for your great theme!

### Description

I tried to modify inline code styles and successfully modified some of them. I followed the instructions in https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/10#issuecomment-102610892.

But I cannot make it through modifying `tranquilpeak\source\_css\base\_base.scss` as follows:

```scss
// inline code
code {
    font-size:        85%;  // map-get($font-size, medium)
    // display:          inline-block;
    font-family:      map-get($font-families, 'code');
    font-weight:      400;
    background-color: rgba(175,184,193,0.2);   // <-- THIS is not working
    padding:          0.2em 0.4em;
    margin: 0;
    border-radius: 6px;
}
```

Chrome dev tools:

![image](https://user-images.githubusercontent.com/8894643/148667383-74294dc0-cfe8-4407-8e6b-2e9e9db42038.png)

You can see it's crossed out. Also you can view the screenshot page [here](https://alanlee.fun/2022/01/08/introducing-upsetplot/#%E4%B8%BB%E8%A6%81%E6%96%B9%E6%B3%95).

### Expected behavior

Change the inline code background color to `rgba(175,184,193,0.2)`:

![image](https://user-images.githubusercontent.com/8894643/148667432-291b025c-6413-4f17-9422-bf369478edb4.png)

### Environment
 - **Operating system with version** : Windows 10
 - **Node version**: v13.14.0
 - **Hexo version**: 3.4.4
 - **Hexo-cli version**: 4.2.0
 - **Tranquilpeak version**:  4.1.3
 - **Site configuration file**: 
 - **Theme configuration file**: 
 - **Hexo plugin**:

### Additional information
- [ ] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
👋 @secsilm, it works, it's just that this property is overridden by another one:
<img width="476" alt="Screen Shot 2022-01-12 at 9 35 19 PM" src="https://user-images.githubusercontent.com/4705626/149272050-27e2302e-0b44-44f1-bd60-257e384ed684.png">

**Comment by secsilm** [comment]
@LouisBarranqueiro Then how do I keep it from being overridden?

**Comment by LouisBarranqueiro** [comment]
I can't really tell because you modified the code of the theme. You need to search in the different files where the property `background-color:#f7f8f8;` is set and remove it.

**Comment by secsilm** [comment]
OK, I finally  get it worked. Here are the steps:

1. Modifying the inline code color as above.
2. Comment out `background` in `_variables.scss` as following:
    ```scss
    // Highlight code
    $highlight: (
        // 'background':  #f7f8f8,  // <-- COMMENT OUT HERE
        'font-size':   1.4rem,
        'border':      1px solid,
        'line-height': 1.3em
    );
    ```
3. The above code will result in losing backround color of  the `pre` code, so we have to specify the background color in `_code.scss`:

    ```scss
    // Reset for tag `pre` and  for class `.gutter`, `.code`, `.tag`
        pre,
        .gutter,
        .code,
        .tag {
            background-color: #f7f8f8;  // <-- MODIFY COLOR HERE
            font-family:      #{map-get($font-families, 'highlight')};
            border:           none;
            padding:          0;
            margin:           0;
            // To override cursor attribute of `.tag` components
            cursor:           text;
        }
    ```
4. `npm run prod`
